### ISSUE TITLE
Query regarding data Set used

### ISSUE THREAD

**Issue by MSPawanRanjith** [kitsook/face#2]
hi Kitsook,
Can you provide source for your data set(imgdb folder).
I have been struggling to get data set for president images.
I would be happy if you at least share the source of your data set.

Thanks in advance.

**Comment by kitsook** [comment]
@MSPawanRanjith I don't own any of the images and so can't provide you the exact files.  But all I did was google the name and save the first few images returned.  Also, depending on which classifier you choose to use, the result can vary.  With the default OpenCV classifier "haarcascade_frontalface_alt.xml", I found that using 5 to 8 photos for each person are enough for training.

**Comment by MSPawanRanjith** [comment]
Thanks @kitsook 
for your detailed answer
