### ISSUE TITLE
Issue in detecting multiple faces

### ISSUE THREAD

**Issue by MSPawanRanjith** [kitsook/face#3]
hi @kitsook,
its again me , i tried implementing ur code.
does it detect 3 or ,more faces?
 if no can u suggest a method to detect 3 or more faces.
if yes , then iam unable to detect, suggest any possible errors.

thanks in advance

**Comment by kitsook** [comment]
The OpenCV cascade classification should be able to detect multiple objects.  Have you tried to tune the parameters to `detectMultiScale`?  Now looking at my code, the naming of my parameters may be a bit confusing.  You may refer to the OpenCV example

https://github.com/opencv/opencv/blob/master/samples/python/facedetect.py

**Comment by MSPawanRanjith** [comment]
The openCv cascade classifier did detect multiple faces. and tried tweaking the threshold in `recognizer.py` , it just started doing fine, with less accuracy. 
thanks i will try tuning `detectMultiScale `
