### ISSUE TITLE
Name the parameters to cv::CascadeClassifier::detectMultiScale correctly

### ISSUE THREAD

**Issue by kitsook** [kitsook/face#4]
Review the paramters passed to the detectMultiScale function
https://github.com/kitsook/face/blob/ab9b95b283a35613c46c6630afe88a1d1eda8c55/detect.py#L39

References:
https://docs.opencv.org/3.0-beta/modules/objdetect/doc/cascade_classification.html
https://github.com/opencv/opencv/blob/master/samples/python/facedetect.py

**Comment by adarshraj3369** [comment]
cv2.error: OpenCV(4.1.0) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1658: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'

what is this error?

**Comment by kitsook** [comment]
> cv2.error: OpenCV(4.1.0) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1658: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'
> 
> what is this error?

You need to to specify the location of the cascade classifiers files.  Edit the location in `conifg.py`.  You should find the classifier files when you install the opencv contrib package.
